### PR TITLE
Attempt to update to GHC 8

### PR DESCRIPTION
**Pull request by deepfire**

### CODE REVIEW

**Comment by deepfire** [comment]
This is in context of #125

**Comment by deepfire** [comment]
@sol, I have made a stab at the problem -- it now seems to build on GHC 8.

**Comment by sol** [comment]
@deepfire A lot of test cases are failing, so I guess this is not yet functional.  I addressed some of them on my [`ghc-8`](https://github.com/sol/doctest/tree/ghc-8) branch.  But there is still more to do.

It's also not clear to me if you code is actually needed or useful in some way.  Have you verified it somehow, if yes how exactly?

**Comment by deepfire** [comment]
@sol, the two test cases failing on my branch are exactly the same that fail on master, AIUI.  Please, correct me if I'm wrong.

**Comment by sol** [comment]
The two test cases that were failing on `master` for GHC < 8 were due to a change in `QuickCheck 2.8.2`.  The failing test cases I was talking about fail for GHC 8 only.  You don't see that on travis.  You have to run them locally.

**Pull request closed without merging**
