### PR TITLE
Automatically expand directories into contained Haskell source files

### PR DESCRIPTION
**Pull request by snoyberg**

### CODE REVIEW

**Comment by bitemyapp** [comment]
Should this enable simplifying the `Setup.hs` in projects like [bloodhound](https://github.com/bitemyapp/bloodhound/blob/master/Setup.hs) and [lens](https://github.com/ekmett/lens/blob/master/Setup.lhs)?

**Comment by snoyberg** [comment]
I have no idea why those projects have complicated `Setup.hs`, or more precisely, what they have to do with doctest. However, I can say that when these two changes are merged in, the Warp doctest changes from:

```haskell
import Test.DocTest
import System.Environment (getEnvironment)

main :: IO ()
main = do
    env <- getEnvironment
    let dist =
            case lookup "HASKELL_DIST_DIR" env of
                Nothing -> "dist"
                Just x -> x
    doctest
        [ concat ["-i", dist, "/build/autogen/"]
        , "-optP-include"
        , concat ["-optP", dist, "/build/autogen/cabal_macros.h"]
        , "Network/Wai/Handler/Warp.hs"
        ]
```

to

```haskell
import Test.DocTest

main :: IO ()
main = doctest ["Network"]
```

**Comment by bitemyapp** [comment]
@snoyberg 

> I have no idea why those projects have complicated Setup.hs, or more precisely, what they have to do with doctest.

It's how the doctests are gathered up. Sort of a long story. It's possible Ed and I missed an opportunity to simplify but nobody I asked in IRC even knew how to get my doctests working other than to point me to the Setup.lhs in `lens`, let alone do it in a cleaner way.

**Comment by snoyberg** [comment]
I don't actually know why the complication is necessary. Is it to make sure that the right packages are depended upon? If that's the motivation, it's unnecessary in the stack case at least, since the package databases will be set correctly.

**Comment by bitemyapp** [comment]
@snoyberg it's so that the doctests can see the dependencies, I think. Perhaps Stack solves this problem itself, I don't know. I'm blocking on some other things for my adoption of `stack` (getting REPL working) right now and doctests have been lower down the list.

**Comment by sol** [comment]
(on hackage)

**Comment by snoyberg** [comment]
Awesome thanks!

**Pull request merged**
