### PR TITLE
Early GHC 8.6 compatibility

### PR DESCRIPTION
**Pull request by quasicomputational**
Since it's so early in the development cycle, there'll probably be more changes, but the one breaking API change doctest is affected by so far is easy to shim.

### CODE REVIEW

**Comment by quasicomputational** [comment]
GHC 8.6 is due to start RCs any day now, so I don't think there are going to be more significant changes in the pipeline.

**Comment by quasicomputational** [comment]
Assuming Travis likes it, I think this is baked.

**Comment by sol** [comment]
@quasicomputational Thanks a lot for working on this.  I squashed into a single commit and pushed to master.

**Comment by sol** [comment]
Released to Hackage as 0.15.1.

**Pull request closed without merging**
