### PR TITLE
Allow ghc-9.10; bump CI

### LINKED ISSUE #420: Support GHC 9.10
https://github.com/BNFC/bnfc/actions/runs/9127670093/job/25098437386?pr=482#step:20:25
> [__0] trying: doctest-0.22.2 (user goal)
> [__1] rejecting: ghc-9.10.1/installed-69c3 (conflict: doctest => ghc>=8.0 && <9.10)

### PR DESCRIPTION
**Pull request by andreasabel**
Closes #420

Blocked on:
- [ ] https://github.com/hspec/setup-haskell/issues/44

### CODE REVIEW

**Comment by andreasabel** [comment]
CI fails due to setup-haskell broken on macos-14 (and does not partially succeed because of `fail-fast: true`).
- https://github.com/hspec/setup-haskell/issues/44

**Comment by sol** [comment]
This is a duplicate of https://github.com/sol/doctest/pull/421.

**Comment by andreasabel** [comment]
> This is a duplicate of #421.

Not in the strong sense, as it also bumps action versions and adds more GHC minor versions to CI.
(Also it allows `ghc-9.11` which hasn't been tested.)

Sorry, I should have checked the open PRs first.

One could cherry-pick the additional changes from here to #421 if they are desired...

**Comment by sol** [comment]
> > This is a duplicate of #421.
> 
> Not in the strong sense, as it also bumps action versions and adds more GHC minor versions to CI. (Also it allows `ghc-9.11` which hasn't been tested.)

All good points 👍

> Sorry, I should have checked the open PRs first.

That's OK, nothing bad happened. I just wanted to make you aware of the effort done by  @sellout.

> One could cherry-pick the additional changes from here to #421 if they are desired...

I am happy with any PR that reaches a mergable state, either this one or #421.

**Comment by sol** [comment]
> I think this PR could be rebased (or whatever) after #421 is merged.

Great, sounds good to me.

**Pull request merged**
