### PR TITLE
Update for GHC 7.10. Some tests fail.

### PR DESCRIPTION
**Pull request by alanz**
I suspect the test source is no longer valid for 7.10, but all the test
files are called Foo.hs

### CODE REVIEW

**Comment by kazu-yamamoto** [comment]
@alanz Thanks.

My implementation is here: https://github.com/kazu-yamamoto/doctest-haskell/tree/ghc-7.10
But this does not pass all tests.

I will compare them when I can find time.

**Comment by kazu-yamamoto** [comment]
I think that @alanz's patch is much better than mine. @sol would you merge @alanz's pull request?

Then, let's try to fix the test failures.

**Comment by sol** [comment]
@kazu-yamamoto @alanz I fully trust you on this.  Please go forward and merge, if you think that is the right thing to do ;)

**Comment by kazu-yamamoto** [comment]
Merged. Sorry for the delay.

**Comment by alanz** [comment]
I did not want to do it because I was not sure about the tests.

**Comment by kazu-yamamoto** [comment]
Yeah. We need to fix tests anyway. But your pull request does not break test results for GHC 7.8 or earlier. That's why I have merged it.

**Pull request merged**
