### PR TITLE
Bump version to 0.20.1

### PR DESCRIPTION
**Pull request by eddiejessup**
As title

### CODE REVIEW

**Review by sol — CHANGES_REQUESTED** [review]
You'll need to run `hpack` so that the `.cabal` file gets updated. Other than that this looks great 👍

**Comment by eddiejessup** [comment]
> You'll need to run `hpack` so that the `.cabal` file gets updated. Other than that this looks great 👍

Oops my bad, done.

**Review by sol — APPROVED** [review]

**Comment by sol** [comment]
Thanks @eddiejessup for taking care of this. Very much appreciated and sorry for the delays.

I think it might be possible to use your approach for older versions of GHC too. If you, or anybody else wants to explore that at some point then I will be more than happy to accept a PR.

**Comment by eddiejessup** [comment]
Not a problem, glad to have it merged, thanks for all the feedback!

Yeah would be nice to have the implementations aligned, I'll take a look if I get the time.

**Pull request merged**
