### PR TITLE
Add --no-magic and --info

### PR DESCRIPTION
**Pull request by sol**

### CODE REVIEW

**Comment by angerman** [comment]
Hi @sol, sorry for providing such bad quality PRs. Thank you for adding the functionality!

I'm just unsure if a change to the external api warrants a bump to 0.12?

**Comment by angerman** [comment]
I have encoded doctest `>= 0.11.3` in the `cabal doctest` action now. So if this is released as `0.11.3`, we should be good.

**Comment by angerman** [comment]
What's holding the merge off? Can I help out somehow?

**Comment by angerman** [comment]
@sol, can we merge this please?

**Comment by sol** [comment]
@angerman Sorry for the late reply!

Regarding your first question, I think we only added new functionality.  We did not remove or change existing functionality.  This is a backward compatible change and does not require a major version bump. (please correct me if you think I missed something)

From what I said earlier at https://github.com/sol/doctest/pull/156#issuecomment-299094651:

> What I now did is: Instead of reviewing your code, I refactored the code and added --no-magic and --info myself (see #159).
>
> Except for the unit tests, my code is untested (that is I did not try it manually).
>
> Can you chime in and
>
> * adapt your Cabal PR to use my branch and check if this works for you
> * give #159 a code review

At the point you merged https://github.com/haskell/cabal/pull/4480, I did not see any use of `--info`.  Did I miss something?  Is it used by now?  Can you point me to the relevant Cabal code?

Can I still ask you for a code review on this PR?

**Comment by angerman** [comment]
I'm perfectly fine with the minor version bump.

Ok. just a quick note regarding the `--info` flag. Cabal queries apps for `--version`, and the version check is for [0.11.3 or later](https://github.com/haskell/cabal/pull/4480/files#diff-bfb1bcbc9e3d8e9b0df8c26d3b316ac6R72). I've just noticed that the [command description](https://github.com/haskell/cabal/pull/4480/files#diff-0346182e8a2987e6b6d529fb7ab340c9R1416) is wrong now (yey strings!) 

I'll see to fixing the cabal command description, and give this another review hopefully later tonight.

**Comment by angerman** [comment]
`--info` will likely come in handy later, when `cabal doctest` (and `cabal new-doctest`) is being extended.  I'm find with the info format as it's the same ghcs `settings` (and the new `llvm-targets` file in ghc 8.4) uses.

**Comment by sol** [comment]
> Cabal queries apps for `--version`

From what I see at https://github.com/haskell/cabal/pull/4480/files#diff-dce7c7ee4de26e5ec445b5db4e52c0beR319, Cabal does not query apps for `--version` in general.  I assume we could easily change that to use `--info`?

**Comment by angerman** [comment]
Is this the definitive end of `--no-magic` for doctest?

**Pull request closed without merging**
